language: go

sudo: false

go:
  - 1.12.x
  - 1.13.x

env:
  - GO111MODULE=on

install: true

git:
  depth: 1

cache:
  directories:
    - vendor
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
    # - $GOPATH/src


script:
  - git checkout $TRAVIS_COMMIT .  # travis.ci will overwrite to master branch
  - go mod vendor
  - go test -race -mod=vendor -coverprofile=coverage.txt -covermode=atomic ./...
  # - go test -bench ./...

after_script:
  - bash <(curl -s https://codecov.io/bash)
