// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gomail "gopkg.in/gomail.v2"
)

// EmailDialer is an autogenerated mock type for the EmailDialer type
type EmailDialer struct {
	mock.Mock
}

// DialAndSend provides a mock function with given fields: m
func (_m *EmailDialer) DialAndSend(m ...*gomail.Message) error {
	_va := make([]any, len(m))
	for _i := range m {
		_va[_i] = m[_i]
	}
	var _ca []any
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...*gomail.Message) error); ok {
		r0 = rf(m...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
