package crypto

import (
	"bytes"
	"context"
	"encoding/hex"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

// writeFakeTongsuo writes a fake tongsuo executable into t.TempDir that records
// every invocation's argv into a log file, answers `version` like Tongsuo 8.5.0
// and fails every other subcommand. It returns the executable path and the
// argv log path. The test is skipped on Windows because the fake is a shell script.
//
// The script is first written to a non-executable source file and then copied
// into place by a cp child process, so this test process never holds a writable
// descriptor on the executable. That avoids ETXTBSY ("text file busy") when a
// parallel test forks while the executable is being written (golang/go#22315).
func writeFakeTongsuo(t *testing.T) (exePath, argvLogPath string) {
	t.Helper()
	if runtime.GOOS == "windows" {
		t.Skip("fake tongsuo is a POSIX shell script")
	}

	dir := t.TempDir()
	argvLogPath = filepath.Join(dir, "argv.log")
	exePath = filepath.Join(dir, "tongsuo")
	script := "#!/bin/sh\n" +
		"printf '%s\\n' \"$*\" >> '" + argvLogPath + "'\n" +
		"if [ \"$1\" = \"version\" ]; then\n" +
		"  echo 'Tongsuo: Tongsuo 8.5.0 (Library: Tongsuo 8.5.0)'\n" +
		"  exit 0\n" +
		"fi\n" +
		"echo 'fake tongsuo: unsupported subcommand' >&2\n" +
		"exit 1\n"
	srcPath := filepath.Join(dir, "tongsuo.src")
	require.NoError(t, os.WriteFile(srcPath, []byte(script), 0o600))

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	//nolint:gosec // G204: test-only copy of a fixture generated by this test.
	out, err := exec.CommandContext(ctx, "/bin/sh", "-c", `cp "$1" "$2" && chmod 700 "$2"`,
		"sh", srcPath, exePath).CombinedOutput()
	require.NoError(t, err, "install fake tongsuo: %s", out)

	return exePath, argvLogPath
}

// readFakeTongsuoArgv returns the argv lines recorded by the fake tongsuo at
// argvLogPath, or an empty slice when the fake was never invoked.
func readFakeTongsuoArgv(t *testing.T, argvLogPath string) []string {
	t.Helper()
	raw, err := os.ReadFile(argvLogPath)
	if os.IsNotExist(err) {
		return nil
	}
	require.NoError(t, err)

	return strings.Split(strings.TrimSpace(string(raw)), "\n")
}

// newSm4TestTongsuo returns a Tongsuo instance for SM4 behavior tests. It prefers
// a real tongsuo binary found in PATH and falls back to the argv-recording fake,
// so that the SM4 tests run on hosts without Tongsuo installed.
func newSm4TestTongsuo(t *testing.T) *Tongsuo {
	t.Helper()
	exePath, err := exec.LookPath("tongsuo")
	if err != nil {
		exePath, _ = writeFakeTongsuo(t)
	}

	ins, err := NewTongsuo(exePath)
	require.NoError(t, err)

	return ins
}

// sm4TestKeyAndPlaintext returns a fresh random 16-byte key and a deterministic
// multi-block plaintext of the given length for SM4 behavior tests.
func sm4TestKeyAndPlaintext(t *testing.T, plaintextLen int) (key, plaintext []byte) {
	t.Helper()
	key, err := Salt(16)
	require.NoError(t, err)

	plaintext = bytes.Repeat([]byte("benign-known-text-"), plaintextLen/18+1)[:plaintextLen]

	return key, plaintext
}

// TestTongsuoSm4KeyNeverInChildArgv verifies that SM4 encryption and decryption,
// including the legacy decoders, never spawn a child process and therefore never
// expose the raw or hex-encoded key in any child argv; regression for issue #44.
//
//nolint:paralleltest // the fake executable is written and executed; avoid ETXTBSY races with parallel forks.
func TestTongsuoSm4KeyNeverInChildArgv(t *testing.T) {
	exePath, argvLogPath := writeFakeTongsuo(t)
	ins, err := NewTongsuo(exePath)
	require.NoError(t, err)

	ctx := context.Background()
	key := []byte("SYNTHETIC-KEY-44")
	iv := []byte("synthetic-iv-044")
	keyHex := hex.EncodeToString(key)
	plaintext := []byte("benign plaintext for the argv capture regression test")

	ciphertext, tag, encErr := ins.EncryptBySm4CbcBaisc(ctx, key, plaintext, iv)
	combined, combinedErr := ins.EncryptBySm4Cbc(ctx, key, plaintext)
	var decErr, combinedDecErr error
	if encErr == nil {
		_, decErr = ins.DecryptBySm4CbcBaisc(ctx, key, ciphertext, iv, tag)
	} else {
		// Exercise the decrypt path with a syntactically valid ciphertext so that
		// any argv exposure on decryption is captured as well.
		_, decErr = ins.DecryptBySm4CbcBaisc(ctx, key, make([]byte, 16), iv, nil)
	}
	if combinedErr == nil {
		_, combinedDecErr = ins.DecryptBySm4Cbc(ctx, key, combined)
	}
	legacy := sm4TestLegacyEncrypt(t, key, plaintext)
	legacyPlain, legacyErr := ins.DecryptBySm4CbcLegacy(ctx, key, legacy)

	argvLines := readFakeTongsuoArgv(t, argvLogPath)
	for _, argv := range argvLines {
		require.NotContains(t, strings.ToLower(argv), keyHex, "hex SM4 key leaked into child argv: %q", argv)
		require.NotContains(t, argv, string(key), "raw SM4 key leaked into child argv")
		require.NotContains(t, argv, "enc", "SM4 must run in-process, got child argv %q", argv)
	}
	require.Equal(t, []string{"version"}, argvLines, "only NewTongsuo may invoke the binary")

	require.NoError(t, encErr)
	require.NoError(t, combinedErr)
	require.NoError(t, decErr)
	require.NoError(t, combinedDecErr)
	require.NoError(t, legacyErr)
	require.Equal(t, plaintext, legacyPlain)
}

// TestTongsuoSm4CbcRejectsEachIVByteFlip verifies that flipping any bit of any IV
// byte in the combined EncryptBySm4Cbc output makes DecryptBySm4Cbc fail without
// returning plaintext; regression for issue #45.
func TestTongsuoSm4CbcRejectsEachIVByteFlip(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ins := newSm4TestTongsuo(t)
	key, plaintext := sm4TestKeyAndPlaintext(t, 48)

	combined, err := ins.EncryptBySm4Cbc(ctx, key, plaintext)
	require.NoError(t, err)

	got, err := ins.DecryptBySm4Cbc(ctx, key, combined)
	require.NoError(t, err)
	require.Equal(t, plaintext, got)

	ivOffset := sm4EnvelopeHeaderSize
	for i := range 16 {
		tampered := bytes.Clone(combined)
		tampered[ivOffset+i] ^= 0x01

		got, err := ins.DecryptBySm4Cbc(ctx, key, tampered)
		require.Error(t, err, "IV byte %d flip must fail authentication", i)
		require.Nil(t, got, "no plaintext may be returned for IV byte %d flip", i)
	}
}

// TestTongsuoSm4CbcBasicRejectsEachIVByteFlip verifies that DecryptBySm4CbcBaisc
// with a nonempty MAC rejects a modified IV for every IV byte position without
// returning plaintext; regression for issue #45.
func TestTongsuoSm4CbcBasicRejectsEachIVByteFlip(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ins := newSm4TestTongsuo(t)
	key, plaintext := sm4TestKeyAndPlaintext(t, 48)
	iv, err := Salt(16)
	require.NoError(t, err)

	ciphertext, tag, err := ins.EncryptBySm4CbcBaisc(ctx, key, plaintext, iv)
	require.NoError(t, err)
	require.Len(t, tag, 32)

	got, err := ins.DecryptBySm4CbcBaisc(ctx, key, ciphertext, iv, tag)
	require.NoError(t, err)
	require.Equal(t, plaintext, got)

	for i := range 16 {
		tamperedIV := bytes.Clone(iv)
		tamperedIV[i] ^= 0x80

		got, err := ins.DecryptBySm4CbcBaisc(ctx, key, ciphertext, tamperedIV, tag)
		require.Error(t, err, "IV byte %d flip must fail authentication", i)
		require.ErrorContains(t, err, "hmac not match")
		require.Nil(t, got, "no plaintext may be returned for IV byte %d flip", i)
	}
}

// TestTongsuoSm4CbcEnvelopeTamperingFails verifies that modifying any magic,
// version, IV, ciphertext, or tag byte of a v1 envelope fails without returning
// plaintext; regression for issue #45.
func TestTongsuoSm4CbcEnvelopeTamperingFails(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ins := newSm4TestTongsuo(t)
	key, plaintext := sm4TestKeyAndPlaintext(t, 40)

	combined, err := ins.EncryptBySm4Cbc(ctx, key, plaintext)
	require.NoError(t, err)
	require.Len(t, combined, sm4EnvelopeHeaderSize+sm4IVSize+48+sm4MACSize)
	require.Equal(t, []byte(sm4EnvelopeMagic), combined[:4])
	require.Equal(t, sm4EnvelopeVersion1, combined[4])

	for i := range combined {
		tampered := bytes.Clone(combined)
		tampered[i] ^= 0x04

		got, err := ins.DecryptBySm4Cbc(ctx, key, tampered)
		require.Error(t, err, "byte %d modification must fail", i)
		require.Nil(t, got, "no plaintext may be returned for byte %d modification", i)
		if i < sm4EnvelopeHeaderSize {
			require.ErrorIs(t, err, ErrSm4CbcMalformedCiphertext, "header byte %d", i)
		} else {
			require.ErrorIs(t, err, ErrSm4CbcHMACMismatch, "byte %d", i)
		}
	}

	t.Run("unknown version with recomputed tag", func(t *testing.T) {
		t.Parallel()
		_, macKey, err := deriveSm4EnvelopeKeys(key)
		require.NoError(t, err)

		forged := bytes.Clone(combined[:len(combined)-sm4MACSize])
		forged[len(sm4EnvelopeMagic)] = 0x02
		forged = append(forged, sm4HMAC(macKey, forged)...)

		got, err := ins.DecryptBySm4Cbc(ctx, key, forged)
		require.ErrorIs(t, err, ErrSm4CbcMalformedCiphertext)
		require.ErrorContains(t, err, "unsupported envelope version 2")
		require.Nil(t, got)
	})

	t.Run("ciphertext block swap", func(t *testing.T) {
		t.Parallel()
		tampered := bytes.Clone(combined)
		ct := tampered[sm4EnvelopeHeaderSize+sm4IVSize : len(tampered)-sm4MACSize]
		first := bytes.Clone(ct[:16])
		copy(ct[:16], ct[16:32])
		copy(ct[16:32], first)

		got, err := ins.DecryptBySm4Cbc(ctx, key, tampered)
		require.ErrorIs(t, err, ErrSm4CbcHMACMismatch)
		require.Nil(t, got)
	})
}

// TestTongsuoSm4CbcEnvelopeMalformedLengthsFail verifies that truncated,
// extended, and malformed-length inputs are rejected as malformed before any
// cryptographic operation, or fail authentication when the truncation keeps a
// structurally valid length; regression for issue #45.
func TestTongsuoSm4CbcEnvelopeMalformedLengthsFail(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ins := newSm4TestTongsuo(t)
	key, plaintext := sm4TestKeyAndPlaintext(t, 33)

	combined, err := ins.EncryptBySm4Cbc(ctx, key, plaintext)
	require.NoError(t, err)

	for n := range len(combined) {
		got, err := ins.DecryptBySm4Cbc(ctx, key, combined[:n])
		require.Error(t, err, "truncation to %d bytes must fail", n)
		require.Nil(t, got)

		structurallyValid := n >= sm4EnvelopeMinSize &&
			(n-sm4EnvelopeHeaderSize-sm4IVSize-sm4MACSize)%16 == 0
		if structurallyValid {
			require.ErrorIs(t, err, ErrSm4CbcHMACMismatch, "truncation to %d bytes", n)
		} else {
			require.ErrorIs(t, err, ErrSm4CbcMalformedCiphertext, "truncation to %d bytes", n)
		}
	}

	for _, extra := range [][]byte{{0x00}, bytes.Repeat([]byte{0x01}, 15), bytes.Repeat([]byte{0x02}, 16)} {
		extended := append(bytes.Clone(combined), extra...)
		got, err := ins.DecryptBySm4Cbc(ctx, key, extended)
		require.Error(t, err, "appending %d bytes must fail", len(extra))
		require.Nil(t, got)
	}

	got, err := ins.DecryptBySm4Cbc(ctx, key, nil)
	require.ErrorIs(t, err, ErrSm4CbcMalformedCiphertext)
	require.Nil(t, got)

	t.Run("basic api ciphertext lengths", func(t *testing.T) {
		t.Parallel()
		iv, err := Salt(16)
		require.NoError(t, err)
		ciphertext, tag, err := ins.EncryptBySm4CbcBaisc(ctx, key, plaintext, iv)
		require.NoError(t, err)

		for _, bad := range [][]byte{nil, ciphertext[:1], ciphertext[:15], ciphertext[:len(ciphertext)-1]} {
			got, err := ins.DecryptBySm4CbcBaisc(ctx, key, bad, iv, tag)
			require.ErrorIs(t, err, ErrSm4CbcMalformedCiphertext, "ciphertext length %d", len(bad))
			require.Nil(t, got)

			got, err = ins.DecryptBySm4CbcBaisc(ctx, key, bad, iv, nil)
			require.ErrorIs(t, err, ErrSm4CbcMalformedCiphertext, "ciphertext length %d without mac", len(bad))
			require.Nil(t, got)
		}

		got, err := ins.DecryptBySm4CbcBaisc(ctx, key, ciphertext[:16], iv, tag)
		require.ErrorIs(t, err, ErrSm4CbcHMACMismatch, "block-aligned truncation must fail authentication")
		require.Nil(t, got)
	})
}

// TestTongsuoSm4CbcWrongKeyFails verifies that both the envelope and the basic
// API reject a wrong key through MAC verification without returning plaintext,
// and that invalid key sizes are rejected; regression for issue #45.
func TestTongsuoSm4CbcWrongKeyFails(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	ins := newSm4TestTongsuo(t)
	key, plaintext := sm4TestKeyAndPlaintext(t, 64)
	wrongKey, err := Salt(16)
	require.NoError(t, err)
	iv, err := Salt(16)
	require.NoError(t, err)

	combined, err := ins.EncryptBySm4Cbc(ctx, key, plaintext)
	require.NoError(t, err)
	got, err := ins.DecryptBySm4Cbc(ctx, wrongKey, combined)
	require.ErrorIs(t, err, ErrSm4CbcHMACMismatch)
	require.Nil(t, got)

	ciphertext, tag, err := ins.EncryptBySm4CbcBaisc(ctx, key, plaintext, iv)
	require.NoError(t, err)
	got, err = ins.DecryptBySm4CbcBaisc(ctx, wrongKey, ciphertext, iv, tag)
	require.ErrorIs(t, err, ErrSm4CbcHMACMismatch)
	require.Nil(t, got)

	for _, badKey := range [][]byte{nil, key[:15], append(bytes.Clone(key), 0x00)} {
		_, err = ins.EncryptBySm4Cbc(ctx, badKey, plaintext)
		require.ErrorContains(t, err, "key should be 16 bytes")
		_, err = ins.DecryptBySm4Cbc(ctx, badKey, combined)
		require.ErrorContains(t, err, "key should be 16 bytes")
		_, _, err = ins.EncryptBySm4CbcBaisc(ctx, badKey, plaintext, iv)
		require.ErrorContains(t, err, "key should be 16 bytes")
		_, err = ins.DecryptBySm4CbcLegacy(ctx, badKey, sm4TestLegacyEncrypt(t, key, plaintext))
		require.ErrorContains(t, err, "key should be 16 bytes")
	}
}

// TestTongsuoSm4CbcHonorsCanceledContext verifies that every SM4 method returns
// an error and no output when its context is already canceled.
func TestTongsuoSm4CbcHonorsCanceledContext(t *testing.T) {
	t.Parallel()
	ins := newSm4TestTongsuo(t)
	key, plaintext := sm4TestKeyAndPlaintext(t, 20)
	iv, err := Salt(16)
	require.NoError(t, err)

	combined, err := ins.EncryptBySm4Cbc(context.Background(), key, plaintext)
	require.NoError(t, err)
	ciphertext, tag, err := ins.EncryptBySm4CbcBaisc(context.Background(), key, plaintext, iv)
	require.NoError(t, err)

	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	out, err := ins.EncryptBySm4Cbc(ctx, key, plaintext)
	require.ErrorIs(t, err, context.Canceled)
	require.Nil(t, out)
	out, err = ins.DecryptBySm4Cbc(ctx, key, combined)
	require.ErrorIs(t, err, context.Canceled)
	require.Nil(t, out)
	out, _, err = ins.EncryptBySm4CbcBaisc(ctx, key, plaintext, iv)
	require.ErrorIs(t, err, context.Canceled)
	require.Nil(t, out)
	out, err = ins.DecryptBySm4CbcBaisc(ctx, key, ciphertext, iv, tag)
	require.ErrorIs(t, err, context.Canceled)
	require.Nil(t, out)
	out, err = ins.DecryptBySm4CbcLegacy(ctx, key, sm4TestLegacyEncrypt(t, key, plaintext))
	require.ErrorIs(t, err, context.Canceled)
	require.Nil(t, out)
}
