package crypto

import (
	"bytes"
	"context"
	"encoding/pem"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

// fakeTongsuoSecretMarker is a stand-in for private key material that the fake
// tongsuo writes to stdout before failing; it must never reach an error.
const fakeTongsuoSecretMarker = "FAKE-PRIVATE-KEY-MATERIAL-0123456789"

// installFakeTongsuoScript installs a fake tongsuo executable into t.TempDir.
// It answers `version` like Tongsuo 8.5.0 and runs body, a POSIX shell
// fragment, for every other subcommand. It returns the executable path. The
// test is skipped on Windows. As in writeFakeTongsuo, the script is copied into
// place by a child process to avoid ETXTBSY with parallel forks.
func installFakeTongsuoScript(t *testing.T, body string) string {
	t.Helper()
	if runtime.GOOS == "windows" {
		t.Skip("fake tongsuo is a POSIX shell script")
	}

	dir := t.TempDir()
	exePath := filepath.Join(dir, "tongsuo")
	script := "#!/bin/sh\n" +
		"if [ \"$1\" = \"version\" ]; then\n" +
		"  echo 'Tongsuo: Tongsuo 8.5.0 (Library: Tongsuo 8.5.0)'\n" +
		"  exit 0\n" +
		"fi\n" + body
	srcPath := filepath.Join(dir, "tongsuo.src")
	require.NoError(t, os.WriteFile(srcPath, []byte(script), 0o600))

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	//nolint:gosec // G204: test-only copy of a fixture generated by this test.
	out, err := exec.CommandContext(ctx, "/bin/sh", "-c", `cp "$1" "$2" && chmod 700 "$2"`,
		"sh", srcPath, exePath).CombinedOutput()
	require.NoError(t, err, "install fake tongsuo: %s", out)

	return exePath
}

// TestTongsuoRunCMDSeparatesStdoutAndStderr verifies the subprocess output
// contract with a fake tongsuo: a successful command returns exactly its
// stdout, never stderr diagnostics, and a failing command's error carries a
// bounded, sanitized stderr excerpt but never stdout, which may hold private
// key material, nor PEM blocks printed to stderr. Regression for the
// coordinator finding that runCMDWithEnv used CombinedOutput.
func TestTongsuoRunCMDSeparatesStdoutAndStderr(t *testing.T) {
	t.Parallel()

	t.Run("success returns stdout only", func(t *testing.T) {
		t.Parallel()
		exe := installFakeTongsuoScript(t,
			"echo 'read EC key' >&2\n"+
				"printf '%s\\n' '-----BEGIN DATA-----' 'payload' '-----END DATA-----'\n"+
				"echo 'writing EC key' >&2\n"+
				"exit 0\n")
		ins, err := NewTongsuo(exe)
		require.NoError(t, err)

		out, err := ins.runCMD(t.Context(), []string{"ec"}, nil)
		require.NoError(t, err)
		require.Equal(t, "-----BEGIN DATA-----\npayload\n-----END DATA-----\n", string(out))
	})

	t.Run("failure never leaks stdout", func(t *testing.T) {
		t.Parallel()
		exe := installFakeTongsuoScript(t,
			"printf '%s\\n' '-----BEGIN PRIVATE KEY-----' '"+fakeTongsuoSecretMarker+"' '-----END PRIVATE KEY-----'\n"+
				"echo 'unable to write key: synthetic diagnostic' >&2\n"+
				"exit 1\n")
		ins, err := NewTongsuo(exe)
		require.NoError(t, err)

		out, err := ins.runCMD(t.Context(), []string{"pkey"}, nil)
		require.Error(t, err)
		require.Nil(t, out)
		require.NotContains(t, err.Error(), fakeTongsuoSecretMarker)
		require.NotContains(t, err.Error(), "BEGIN PRIVATE KEY")
		require.Contains(t, err.Error(), "unable to write key: synthetic diagnostic")
	})

	t.Run("pem printed to stderr is redacted", func(t *testing.T) {
		t.Parallel()
		exe := installFakeTongsuoScript(t,
			"echo 'bad input, dumping:' >&2\n"+
				"printf '%s\\n' '-----BEGIN EC PRIVATE KEY-----' '"+fakeTongsuoSecretMarker+"' >&2\n"+
				"exit 2\n")
		ins, err := NewTongsuo(exe)
		require.NoError(t, err)

		_, err = ins.runCMD(t.Context(), []string{"ec"}, nil)
		require.Error(t, err)
		require.Contains(t, err.Error(), "bad input, dumping:")
		require.NotContains(t, err.Error(), fakeTongsuoSecretMarker)
		require.NotContains(t, err.Error(), "BEGIN EC PRIVATE KEY")
	})

	t.Run("stderr excerpt is bounded", func(t *testing.T) {
		t.Parallel()
		exe := installFakeTongsuoScript(t,
			"i=0\nwhile [ $i -lt 2000 ]; do echo 'noisy diagnostic line' >&2; i=$((i+1)); done\nexit 1\n")
		ins, err := NewTongsuo(exe)
		require.NoError(t, err)

		_, err = ins.runCMD(t.Context(), []string{"x509"}, nil)
		require.Error(t, err)
		require.Contains(t, err.Error(), "noisy diagnostic line")
		require.Less(t, len(err.Error()), 2048)
	})
}

// TestTongsuoNewPrikeyWithPasswordOutputIsPurePEM verifies with the real
// tongsuo binary that NewPrikeyWithPassword returns only PEM data: the output
// starts with "-----BEGIN" and nothing but whitespace follows the PEM blocks,
// so strict PEM parsers accept it. CombinedOutput used to prefix it with the
// "read EC key" / "writing EC key" stderr chatter.
func TestTongsuoNewPrikeyWithPasswordOutputIsPurePEM(t *testing.T) {
	t.Parallel()
	ins := newSecurityTestTongsuo(t)

	out, err := ins.NewPrikeyWithPassword(t.Context(), "synthetic-password")
	require.NoError(t, err)
	require.True(t, bytes.HasPrefix(out, []byte("-----BEGIN")), "output must start with PEM, got %q",
		firstLineForTest(out))

	rest := out
	blocks := 0
	for {
		var block *pem.Block
		block, rest = pem.Decode(rest)
		if block == nil {
			break
		}
		blocks++
	}
	require.Equal(t, 1, blocks)
	require.Empty(t, bytes.TrimSpace(rest), "no text may follow the PEM block")
}

// firstLineForTest returns the first line of b as a string, for failure messages.
func firstLineForTest(b []byte) string {
	line, _, _ := bytes.Cut(b, []byte("\n"))
	return string(line)
}

// TestTongsuoExactValidityProbeReadsHelpFromStderr verifies that the exact
// validity capability probe still detects -not_before/-not_after on Tongsuo
// 8.5 after stdout and stderr are captured separately: `-help` writes its
// summary to stderr, so the probe must inspect it.
func TestTongsuoExactValidityProbeReadsHelpFromStderr(t *testing.T) {
	t.Parallel()
	ins := newSecurityTestTongsuo(t)

	exact, err := ins.probeExactValidity(t.Context())
	require.NoError(t, err)
	require.True(t, exact, "Tongsuo 8.5 supports -not_before and -not_after")
}
