name: Linter

on:
  push:
    branches: [ master, develop ]
    paths-ignore:
      - "**/*.md"
      - ".scripts/*.sh"

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13', '1.14', '1.15', '1.16', '1.17' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            vendor
            $HOME/.cache/go-build
            $GOPATH/pkg/mod
          key: ${{ runner.os }}-go-utils-deps

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - run: go version
      - run: pwd
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: go mod vendor
      - run: go vet
      - run: go test -race ./...
